grupo5i/alumno/urls.py
from django.urls import path
from alumno import views

urlpatterns = [
    path('', views.index_vista,name="index_vista"),
    path("alumno/<int:id>",views.alumno_vista),
]

grupo5i/primaria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('alumno.urls')),
]

grupo5i/alumno/models.py
from django.db import models

# Create your models here.

class Alumno(models.Model):
    apaterno= models.CharField(max_length=50, verbose_name="Apellido Paterno")
    amaterno= models.CharField(max_length=50, verbose_name="Apellido Materno")
    nombre=models.CharField(max_length=100, verbose_name="Nombre (s)")
    fecha_nacimiento= models.DateField(verbose_name="Fecha de nacimiento", null=False, blank=False)
    fecha_ingreso= models.DateField(verbose_name="Fecha de ingreso", null=False, blank=False)

    class Meta:
        db_table="Alumnos"
        verbose_name="Alumno"
        verbose_name_plural="Alumnos"
    
    def __str__(self) -> str:
        return self.nombre

class Frase(models.Model):
    comentario= models.TextField(verbose_name="Comentario", max_length=400)
    Alumno_fk= models.ForeignKey(Alumno, on_delete=models.CASCADE)

    class Meta:
        verbose_name="Frase"
        verbose_name_plural="Frases"

grupo5i/alumno/views.py
from django.shortcuts import render,get_object_or_404
from .models import Alumno

# Create your views here.

def index_vista(request):
    misalumnos=Alumno.objects.all().order_by("id")
    return render(request, "index.html",{"misalumnos":misalumnos})
def alumno_vista(request,id):
    alumno= get_object_or_404(Alumno,id=id)
    return render(request, "Alumno.html",{"objeto":alumno})

grupo5i/alumno/templates/Alumno.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>comentarios</title>
</head>
<body>
    <h1>un alumno y sus mensas osea comentarips</h1>
    <h1>{{objeto.nombre}}</h1>
    <ul>
    {% for i in objeto.frase_set.all %}
    <li> {{i.comentario}}</li>

    {% endfor %}
    </ul>
</body>
</html>

grupo5i/alumno/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href= {% static "estilo.css" %}>
    <title>P_Edgar</title>
</head>
<body>
    <h1>listado de alumnos</h1>
    <hr>
    <ul>
    {% for i in misalumnos %}
    <li> <a href="alumno/{{i.id}}">{{i.nombre}}</a></li>
    {% endfor %}
    </ul>
    <script src="{% static "scripts.js" %}"> </script>
</body>
</html>